### PR TITLE
SLSP-34

### PR DESCRIPTION
**Pull request by willbryanta**
edit: I believe this is all we need for the reviewService, as request validation will be handled server-side.

### CODE REVIEW

**Review by Zarbba — COMMENTED** [review]
This looks good for create but we'll also need delete and edit. At this stage I don't think we need show but not sure. Depends on how we choose to implement some things.

**Review by EddieC97 — COMMENTED** [review]
Could you clarify whether users need to be signed in to create a review, or can anyone submit one? 

If authentication is required, we will need to implement JWT authentication.

**Review by EddieC97 — APPROVED** [review]
The changes look good!

**Comment by willbryanta** [comment]
Auth for both creating and updating

**Pull request merged**
